## Версия docker-compose
version: '3.7'
services:
    mysql:
        image: mariadb
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./db:/var/lib/mysql
            - /etc/localtime:/etc/localtime
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/conf.d:/etc/nginx/
            - ./asterisk/records:/var/www/mp3
            - /etc/localtime:/etc/localtime
    fastagi:
        image: java:8
        ports:
            - "4573:4573"
        volumes:
            - ./fastagi:/usr/src/myapp
            - /etc/localtime:/etc/localtime
        command: bash -c "cd /usr/src/myapp && java -cp asterisk-java.jar:mongo.jar:. org.asteriskjava.fastagi.DefaultAgiServer"
    asterisk:
        image: mfc/asterisk
        build: ./build
        restart: always
        volumes:
            - ./asterisk/etc:/etc/asterisk
            - ./asterisk/outgoing:/var/spool/asterisk/outgoing
            - ./asterisk/sounds:/var/lib/asterisk/sounds
            - ./asterisk/records:/var/spool/asterisk/monitor
            - ./asterisk/logs:/var/log/asterisk
            - ./asterisk/odbc.ini:/etc/odbc.ini
            - /etc/localtime:/etc/localtime
        network_mode: "host"
    qpanel:
        image: mfc/qpanel
        build: ./qpanel
        restart: always
        ports:
            - 5000:5000
        volumes:
            - ./qpanel/config.ini:/qpanel/config.ini
        environment:
            QPANEL_USER: ${QPANEL_USER}
            QPANEL_PWD: ${QPANEL_PWD}
            ASTERISK_HOST: ${ASTERISK_HOST}
networks:
    default:
      ipam:
        driver: default
        config:
          - subnet: 10.97.199.0/24
