## Версия docker-compose
version: '3.7'
services:
    mysql:
        image: mariadb
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - datavolume01:/var/lib/mysql
            - /etc/localtime:/etc/localtime
        environment:
           MYSQL_ROOT_PASSWORD: HgJKKJkdkdsdlkjksldfjklsefjs8u894wijfdkslfj!fdfsdfsfsfgdsgdffdsgChngeMEIVeryStrong
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /opt/evocc/nginx/conf.d:/etc/nginx/
            - /opt/evocc/asterisk/records:/var/www/mp3
            - /etc/localtime:/etc/localtime
    fastagi:
        image: java:8
        ports:
            - "4573:4573"
        volumes:
            - /opt/evocc/fastagi:/usr/src/myapp
            - /etc/localtime:/etc/localtime
        command: bash -c "cd /usr/src/myapp && java -cp asterisk-java.jar:mongo.jar:. org.asteriskjava.fastagi.DefaultAgiServer"
    asterisk:
        image: evocc/callcenterv1
        restart: always
        volumes:
            - /opt/evocc/asterisk/etc:/etc/asterisk
            - /opt/evocc/asterisk/sounds:/var/lib/asterisk/sounds
            - /opt/evocc/asterisk/records:/var/spool/asterisk/monitor
            - /opt/evocc/asterisk/odbc.ini:/etc/odbc.ini
            - /etc/localtime:/etc/localtime
        network_mode: "host"
networks:
    default:
      ipam:
        driver: default
        config:
          - subnet: 10.99.199.0/24
volumes:
    datavolume01: {}
